# Generated by Django 3.1.7 on 2021-02-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_auto_20210223_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='Bio',
            field=models.TextField(blank=True, help_text='Enter a brief description of the speaker', max_length=1000, null=True),
        ),
    ]
