# Generated by Django 3.1.7 on 2021-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_speaker_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='Bio',
            field=models.TextField(blank=True, help_text='Enter a brief description of the speaker', max_length=5000, null=True),
        ),
    ]
