# Generated by Django 3.1.7 on 2021-02-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0005_auto_20210224_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speeches',
            name='Post_Summary',
            field=models.TextField(help_text='Enter a brief description of the speech', max_length=10000),
        ),
    ]
