# Generated by Django 3.1.7 on 2021-02-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0006_auto_20210224_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speeches',
            name='Post_Summary',
            field=models.TextField(help_text='Enter a brief description of the speech', max_length=50000),
        ),
    ]
