# Generated by Django 3.1.7 on 2021-02-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
